### ISSUE TITLE
反馈一些问题

### ISSUE THREAD

**Issue by shigma** [ForkKILLET/SudoerOfMyself#2]
首先做的很有趣！

---

两个疑似 bug：

![4_`6XT4}Y`%E@`L}4UX4J`W](https://user-images.githubusercontent.com/33423008/162573679-2598d9c6-4f43-4ea8-8972-b7e015e0a559.png)

![`UXW$_Y}NT7P4D@0KR6P D8](https://user-images.githubusercontent.com/33423008/162573683-27c926aa-e299-4a96-9509-e4cd815ba7d6.png)

两个建议：

![HC9Q$@ V}6YDXY_D (NSA$9](https://user-images.githubusercontent.com/33423008/162573701-c4fb4115-f1f2-4e24-8e6d-e0e8c240c503.png)

建议 tab 改 2/4 spaces 不然看起来太难受了。

还有就是滚动条的位置和样式我也建议改一改。

**Comment by ForkKILLET** [comment]
感谢反馈

回复
- `ls` 出错是个已知问题，在修了，但是复现条件还不是很清楚，如果能提供一下就太好了！
- `sandbox` 是一个测试命令，用法是 `sandbox <javascript URL>`，可能不久会移除。
- `cat bin/xxx` 断行是因为 js 中的 `"\n"` 打包时被 minify 成了真正的换行符（会节省一个字符），而 `xterm.js` 中换行和回车是分开的，这就导致了断行。`cat -A` 可以用十六进制显示控制字符，体验更佳。

**Comment by ForkKILLET** [comment]
![图片](https://user-images.githubusercontent.com/35412022/162574082-a47116a1-a0de-4029-9b59-cd2e7a459719.png)
滚动条的话我这边是这样的，感觉还行

有些设备上好像是会有错位的现象，能不能提供一下您的设备信息？

**Comment by shigma** [comment]
- 系统：windows 10 21H2 19044.1586
- 浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

**Comment by shigma** [comment]
ls 的话 bin 是好的，home 和 dev 都稳定产生报错

**Comment by ForkKILLET** [comment]
笑死，不小心把 minify 关了，我说怎么那么多空格

**Comment by ForkKILLET** [comment]
`ls` 的问题预计今天能修复，这取决于我什么时候做完作业

**Comment by ForkKILLET** [comment]
![图片](https://user-images.githubusercontent.com/35412022/162574992-cec8ad27-4ed5-4545-9350-af625fa819bd.png)
还是不能确定 `ls` core dump 怎么复现的，之前我测试一直是这样好的

目前这一套 JSON 文件系统问题很大，等基于 WASM 的文件系统 ext0 写好了应该会安全很多

**Comment by ForkKILLET** [comment]
应该修好了
